- name: Remove stack
  community.general.docker_stack:
    name: "{{ stack_application_stack_name }}"
    state: absent

- name: Stack of application file
  ansible.builtin.template:
    src: stack.yaml
    dest: "{{ swarm_compose_temp_path }}"
    mode: "0644"

- name: Deploy stack from compose file
  community.docker.docker_stack:
    name: "{{ stack_application_stack_name }}"
    state: present
    compose:
      - "{{ swarm_compose_temp_path }}/stack.yaml"
    with_registry_auth: true
