- name: Create directories for applications
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    recurse: true
  loop: "{{ application_dirs }}"

- name: Open ports from a list to UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_ports }}"
  when: ufw_ports is defined

- name: Open UPD ports from a list to UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ ufw_ports_udp }}"
  when: ufw_ports_udp is defined
