---
- name: SERVICES - Create data dir
  ansible.builtin.file:
    path: /data/{{ item }}
    owner: "{{ nas_user }}"
    group: "{{ nas_user }}"
    state: directory
    mode: '0755'
  loop:
    - torrents/movies
    - torrents/tv
    - media/movies
    - media/tv

- name: SERVICES - Deploy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/docker-compose.yml
    mode: '0644'

- name: SERVICES - Bring up the docker-compose services
  community.docker.docker_compose_v2:
    project_src: /opt
    state: present

- name: SERVICES - Ensure correct owner and permissions
  ansible.builtin.file:
    path: /opt
    owner: "{{ nas_user }}"
    group: "{{ nas_user }}"
    recurse: true
